# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16d7ed17fb531edbb6972ccee392c9ccb35542194f5a2f74dfa4f1babfac3c9809520a604e290ed452979db5a5ea29c3279f9826db29eb33d4274d7ffa072e3e

test:
  secret_key_base: cdb4bd109b73ecd6e97aab2437cfc2b04cbce63d91e9aef33819e059eac3b9c83a3e0d1c0b221b7f4b94f78ad8d582e00449664765377f30a5cfba4543d07ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
